config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/journeys', to: 'pages#journeys'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  resources :charging_stations

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :charging_stations, only: [] do
        resources :rentals, only: [ :index, :create ]
      end

      get 'rentals/:pan_hash', :to => 'rentals#find_by_pan_hash'
      get 'charging_stations/:charging_station_id/rentals/:status', :to => 'rentals#find_all_to_be_closed'
      patch 'rentals/:id', :to => 'rentals#update'
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  <head>
    <!-- <link rel="stylesheet" type="text/css" href="style.css"> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

<!-- Footer -->
<div class="footer">
  <footer class="page-footer font-small indigo mt-4">
    <!-- Footer Links -->
    <div class="container">
      <!-- Grid row-->
      <div class="row text-center d-flex justify-content-center pt-5 mb-3">
        <div class="col-md-2">
        </div>
        <!-- Grid column -->
        <div class="col-md-2 mb-3">
          <h6 class="text-uppercase font-weight-bold">
            <%= link_to about_path do %>
              <p>About us</p>
            <% end %>
          </h6>
        </div>
        <!-- Grid column -->
        <div class="col-md-2 mb-3">
<!--           <h6 class="text-uppercase font-weight-bold">
            <a href="#!">News</a>
          </h6> -->
        </div>
        <!-- Grid column -->
        <div class="col-md-2 mb-3">
   <!--        <h6 class="text-uppercase font-weight-bold">
            <a href="#!">Help</a>
          </h6> -->
        </div>
        <!-- Grid column -->
        <div class="col-md-2 mb-3">
          <h6 class="text-uppercase font-weight-bold">
            <a href=<%= contact_path %>>Contact</a>
          </h6>
        </div>
        <!-- Grid column -->
        <div class="col-md-2">
        </div>
      </div>
      <!-- Grid row-->
      <hr class="rgba-white-light" style="margin: 1% 15%;">
      <!-- Grid row-->
      <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">
        <!-- Grid column -->
        <div class="col-md-8 col-md-offset-2 mt-5">
          <p style="line-height: 1.7rem">Follow us on social media to get updated on our progress </p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row-->
      <hr class="clearfix d-md-none rgba-white-light" style="margin: 0% 15% 1%;">
      <!-- Grid row-->
      <div class="row pb-3">
        <!-- Grid column -->
        <div class="col-md-12 text-center">
          <div class="mb-5 flex-center">

            <!-- Facebook -->
            <a href="https://www.facebook.com/thorenergyltd/" class="fb-ic">
              <i class="fa fa-facebook fa-lg white-text mr-md-4"> </i>
            </a>

            <!-- Twitter -->
<!--             <a href="" class="tw-ic">
              <i class="fa fa-twitter fa-lg white-text mr-md-4"> </i>
            </a> -->

            <!-- Google +-->
<!--             <a href="" class="gplus-ic">
              <i class="fa fa-google-plus fa-lg white-text mr-md-4"> </i>
            </a> -->

            <!--Linkedin -->
            <a href="https://www.linkedin.com/company/thor-energy-ltd/" class="li-ic">
              <i class="fa fa-linkedin fa-lg white-text mr-md-4"> </i>
            </a>

            <!--Instagram-->
            <a href="https://www.instagram.com/thorenergyltd/" class="ins-ic">
              <i class="fa fa-instagram fa-lg white-text mr-md-4"> </i>
            </a>

            <!--Pinterest-->
<!--             <a href="" class="pin-ic">
              <i class="fa fa-pinterest fa-lg white-text"> </i>
            </a> -->
          </div>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row-->
    </div>
    <!-- Footer Links -->
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright: Thor Energy
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
</div>

app/views/shared/_navbar.html.erb
<!-- <div class="navbar-wagon navbar-fixed-top"> -->
<div class="navbar-wagon <%= 'navbar-fixed-top' if params[:action] == 'home' || current_page?(controller: '/charging_stations', action: 'index') || current_page?(controller: '/pages', action: 'about')%>">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Locations", charging_stations_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "About Us", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Contact Us", contact_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "cog.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Links when logged out -->
      <%= link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Locations", charging_stations_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "About Us", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Contact Us", contact_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- LOGIN LINK (when logged out) -->
      <%= link_to "Sign Up", "", class: "bio-btn", data: {toggle:"modal", target: "#signUpModalCenter"}, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Log In", "", class: "bio-btn", data: {toggle:"modal", target: "#logInModalCenter"}, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- MOBILE DROPDOWN LIST -->

  <% if user_signed_in? %>
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <a href = <%= charging_stations_path %>> <i class="fas fa-map-marker-alt"></i></a>
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href= <%= root_path %> >Home</a></li>
        <li><a href= <%= user_path(current_user) if current_user %> >Profile</a></li>
        <li><a href= <%= charging_stations_path %> >Locations</a></li>
        <li><a href=<%= about_path %>>About Us</a></li>
        <li><a href=<%= contact_path %>>Contact Us</a></li>
        <li><%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>
          <%= t(".sign_out", default: "Log out") %>
          <% end %></li>
        <li class="app-bttn-yellow">Download the APP</li>
      </ul>
    </div>
  </div>
  <% else %>
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <a href = <%= charging_stations_path %>> <i class="fas fa-map-marker-alt"></i></a>
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href= <%= root_path %> >Home</a></li>
          <li><a href= <%= charging_stations_path %> >Locations</a></li>
          <li><a href= <%= about_path %>>About Us</a></li>
          <li><a href= <%= contact_path %>>Contact Us</a></li>
          <li><a href= <%= link_to "Sign Up", "", class: "bio-btn", data: {toggle:"modal", target: "#signUpModalCenter"} %></a></li>
          <li><a href=<%= link_to "Log In", "", class: "bio-btn", data: {toggle:"modal", target: "#logInModalCenter"} %></a></li>
          <li class="app-bttn-yellow">Download the APP</li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

<%= render 'pages/log_in' %>
<%= render 'pages/sign_up' %>