config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/journeys', to: 'pages#journeys'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  resources :charging_stations

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :charging_stations, only: [] do
        resources :rentals, only: [ :index, :create ]
      end

      get 'rentals/:pan_hash', :to => 'rentals#find_by_pan_hash'
      get 'charging_stations/:charging_station_id/rentals/:status', :to => 'rentals#find_all_to_be_closed'
      patch 'rentals/:id', :to => 'rentals#update'
    end
  end
end

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(96,100,112,0.8) 0%, rgba(96,100,112,.8) 50%), url(<%= image_path('banner.jpg') %>)">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
        <h1>Low on<br> phone battery?</h1>
        <p id="yellow-dash">_____</p>
        <div class="form-inline">
          <%= form_tag charging_stations_path, method: :get do %>
            <span class="input-holder">
              <%= text_field_tag :query,
                params[:query],
                class: "form-control-banner autocomplete",
                placeholder: "Enter location....."
              %>
              <%= link_to charging_stations_path + "?current_location" do %>
                <i class="fas fa-crosshairs"></i>
              <% end %>
            </span>
            <%= submit_tag "Search", class: "bttn-yellow"  %>
          <% end %>
        </div>
        <div class="phone-locate-box">
          <%= link_to charging_stations_path + "?current_location", class: "phone-locate text-center" do %>
            <i class="fas fa-crosshairs"></i>
            <p>Use current location</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_bio.html.erb
<% @bios.each do |bio| %>
  <div class="modal fade" id="<%= bio[:first_name].downcase %>Modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">
            <%= "#{bio[:first_name]} #{bio[:last_name]}" %>
          </h5>
          <em><p><%= "#{bio[:email]}" %></p></em>
          <em><p><%= "Age: #{bio[:age]}" %></p></em>
        </div>
        <div class="modal-body">
          <%= bio[:description] %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/_how.html.erb
<div class="banner-2">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1>How it works</h1>
        <p id="line">____</p>
      </div>
    </div>
    <div class="how-flex-box">
      <div class="how-flex-item">
        <div class="how">
          <p class="mini-header">Find a charger nearest you</p>
          <p>One tap and you will be directed towards the charger nearest your location. When you get there, you'll have a charger waiting for you.</p>
          <p class="mini-header">Pick up and drop off</p>
          <p>Running late for a meeting? Going out for drinks? No problem. Rest easy knowing you can count on your phone. When you're finished, simply locate the nearest dispenser and drop off the charger at your convenience.</p>
        </div>
      </div>
      <div class ="how-flex-item how-flex-box">
        <div class="phone">
          <img src= <%= image_path('phone.png') %> alt="">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_log_in.html.erb
<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#logInModalCenter">
  Launch demo modal
</button> -->

<!-- Modal -->
<div class="modal fade" id="logInModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Log In</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-inputs">
            <%= f.input :email, required: false, autofocus: true %>
            <%= f.input :password, required: false %>
            <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
          </div>
      </div>
      <div class="modalfooter">
        <div class="form-actions">
          <%= f.button :submit, "Log in", class: "btn btn-primary" %>
        </div>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_pricing.html.erb
<div class="banner-3">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 pricing-header">
        <h1>Pricing</h1>
        <p>____</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-7">
        <div class="pricing-card-container">
          <div class="pricing-card-row-1">
            <h1>Simple and Transparent</h1>
          </div>
          <div class="pricing-card-row-2">
            <div class="pricing-card-row-2-a">
              <p><strong class="price">£3</strong></p>
              <p>price if battery is<br> returned within 23hrs</p>
            </div>
            <div class="pricing-card-row-2-b">
              <p><strong class="price">£10</strong></p>
              <p>price if battery is <br> not returned in 23 hrs</p>
            </div>
          </div>
          <div class="pricing-card-row-3">
            <p><i class="fas fa-bolt"></i> Use your card at the dispenser to get a powerbank</p>
            <p><i class="far fa-clock"></i> Each powerbank rental is good for a 23hr duration</p>
            <p><i class="fas fa-credit-card"></i> Your card is charged after the rental duration expires</p>
            <p></p>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-md-5">
        <div class="pricing-create-account-container">
          <h1>Sign Up</h1>
          <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= f.error_notification %>

            <div class="row">
              <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-10 col-md-offset-1">
                <%= f.input :email, required: true, autofocus: false %>
                <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
                <%= f.input :password_confirmation, required: true %>
              <div class="button-center">
                <%= f.button :submit, "Sign up", class:"bttn-yellow" %>
              </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_sign_up.html.erb
<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  Launch demo modal
</button> -->

<!-- Modal -->
<div class="modal fade" id="signUpModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content black">
      <div class="modal-header black">
        <h5 class="modal-title" id="exampleModalLongTitle">Sign Up For An Account</h5>
        <button type="button" class="close black" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body black">
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :email, required: true, autofocus: true %>
            <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
            <%= f.input :password_confirmation, required: true %>
          </div>
      <div class="modalfooter black">
        <div class="form-actions">
          <%= f.button :submit, "Sign Up", class: "btn btn-primary" %>
        </div>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_slideshow.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
  </ol>
<!--   <h1 class="main-header">CHARGING MADE EASY</h1> -->
  <!-- Wrapper for slides -->

    <div class="carousel-inner">
      <div class="item active">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_1.jpg') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_2.jpg') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_3.jpg') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_4.jpg') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_5.jpg') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_6.jpg') %>)">
        </div>
      </div>
    </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/pages/_slideshow_mobile.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>
  </ol>
<!--   <h1 class="main-header">CHARGING MADE EASY</h1> -->
  <!-- Wrapper for slides -->

    <div class="carousel-inner">
      <div class="item active">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_mobile_01.png') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_mobile_02.png') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_mobile_03.png') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_mobile_04.png') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_mobile_05.png') %>)">
        </div>
      </div>

      <div class="item">
        <div class="car-img" style="background-image: url(<%= image_path('instructional_slides_mobile_06.png') %>)">
        </div>
      </div>
    </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/pages/_team.html.erb
<div class="team">
  <div class="container team">
    <h1>The Team</h1>
    <h3>The Founders</h3>
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag 'giovanni_yellow.png', class: "avatar-team" %>
            </div>
            <div class="back">
              <%= image_tag 'avatar_giovanni.png', class: "avatar-team" %>
            </div>
          </div>
        </div>
        <div class="bio">
          <h4>Giovanni Fantini</h4>
          <p>CEO & Co-founder</p>
          <%= link_to "Read More", "", class: "bio-btn", data: {toggle:"modal", target: "#giovanniModal"} %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag 'giacomo_yellow.png', class: "avatar-team" %>
            </div>
            <div class="back">
              <%= image_tag 'avatar_giacomo.png', class: "avatar-team" %>
            </div>
          </div>
        </div>
        <div class="bio">
          <h4>Giacomo Camisassa</h4>
          <p>Co-founder</p>
          <%= link_to "Read More", "", class: "bio-btn", data: {toggle:"modal", target: "#giacomoModal"} %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag 'matteo_yellow.png', class: "avatar-team" %>
            </div>
            <div class="back">
              <%= image_tag 'avatar_matteo.png', class: "avatar-team" %>

            </div>
          </div>
        </div>
        <div class="bio">
          <h4>Matteo de Cicco</h4>
          <p>CTO & Co-founder</p>

          <%= link_to "Read More", "", class: "bio-btn", data: {toggle:"modal", target: "#matteoModal"} %>

        </div>
      </div>
    </div>

    <h3>Consultants and collaborators</h3>

    <div class="row">
      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag 'laura_yellow.png', class: "avatar-team" %>
            </div>
            <div class="back">
              <%= image_tag 'avatar_laura.png', class: "avatar-team" %>
            </div>
          </div>
        </div>
        <div class="bio">
          <h4>Laura Lezcano</h4>
          <p>Graphic Designer</p>
          <%= link_to "Read More", "", class: "bio-btn", data: {toggle:"modal", target: "#lauraModal"} %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag 'riccardo_yellow.png', class: "avatar-team" %>
            </div>
            <div class="back">
              <%= image_tag 'avatar_riccardo.png', class: "avatar-team" %>
            </div>
          </div>
        </div>
        <div class="bio">
          <h4>Riccardo Arciulo</h4>
          <p>Senior Engineer Electronics and Mechanics</p>
          <%= link_to "Read More", "", class: "bio-btn", data: {toggle:"modal", target: "#riccardoModal"} %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag 'alessandro_yellow.png', class: "avatar-team" %>
            </div>
            <div class="back">
              <%= image_tag 'avatar_alessandro.png', class: "avatar-team" %>
            </div>
          </div>
        </div>
        <div class="bio">
          <h4>Alessandro</h4>
          <p>Senior Fullstack Developer</p>
          <%= link_to "Read More", "", class: "bio-btn", data: {toggle:"modal", target: "#alessandroModal"} %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag 'sam_yellow.png', class: "avatar-team" %>
            </div>
            <div class="back">
              <%= image_tag 'avatar_sam.png', class: "avatar-team" %>
            </div>
          </div>
        </div>
        <div class="bio">
          <h4>Sam Jenkins</h4>
          <p>Junior Fullstack Developer</p>
          <%= link_to "Read More", "", class: "bio-btn", data: {toggle:"modal", target: "#samModal"} %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-4 col-md-4">
        <div class="flip-container" ontouchstart="this.classList.toggle('hover');">
          <div class="flipper">
            <div class="front">
              <%= image_tag 'masaki_yellow.png', class: "avatar-team" %>
            </div>
            <div class="back">
              <%= image_tag 'avatar_masaki.png', class: "avatar-team" %>
            </div>
          </div>
        </div>
        <div class="bio">
          <h4>Masaki Noguchi</h4>
          <p>Junior Fullstack Developer</p>
          <%= link_to "Read More", "", class: "bio-btn", data: {toggle:"modal", target: "#masakiModal"} %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render 'pages/bio' %>

app/views/pages/about.html.erb
<div class="about">
  <div class="container about-us">
    <h1>About Us</h1>
    <div class="row row-relative">
      <div class="col-xs-12 col-sm-5">
        <h3>VISION</h3>
        <p id ="yellow-line">___________</p>
        <p>As the fuel of all future human activity, electricity will be independently and sustainably produced, widely and comfortably consumed, efficiently and democratically commoditised.</p>
      </div>
      <div class="col-sm-2 hidden-xs">
        <%= image_tag "hammer.png", class: "big-hammer" %>
      </div>
      <div class="col-xs-12 col-sm-5">
        <div class="about-us-mission">
          <h3>MISSION</h3>
          <p id ="yellow-line">___________</p>
          <p>Becoming a new type of energy intermediary by establishing new distribution infrastructure and a parallel marketplace to connect moving customers with independent, sustainable producers. </p>
        </div>
      </div>
      <div class="about-us-img hidden-sm hidden-md hidden-lg">
        <%= image_tag "hammer.png", class: "about-hammer" %>
      </div>
    </div>
  </div>
</div>

<%= render 'pages/team' %>
<% content_for :page_scripts do %>
  <%= javascript_pack_tag "home" %>
<% end %>

app/views/pages/contact.html.erb
<div class="min-form-height">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
        <h1 class="text-center">Contact us</h1>
        <form action="https://formspree.io/info@thor.energy"
              method="POST"
              class="">
          <div class="form-group">
            <label for="user-email">Email address</label>
            <input name="email" type="email" class="form-control" id="user-email" placeholder="Email">
          </div>
          <div class="form-group">
            <label for="user-message">Message</label>
            <textarea name="message "class="form-control" rows="8"></textarea>
          </div>
          <button type="submit" class="btn bttn-yellow">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% require "browser/aliases" %>
<% Browser::Base.include(Browser::Aliases) %>

<%= render 'banner' %>
<%= render 'how' %>
<% if browser.mobile? %>
  <%= render 'slideshow_mobile' %>
<% else %>
  <%= render 'slideshow' %>
<% end %>

<%= render 'pricing' %>
<% content_for :page_scripts do %>
  <%= javascript_pack_tag "home" %>
  <%= javascript_pack_tag "transparent_navbar_on_scroll" %>
<% end %>

app/views/pages/journeys.html.erb
<h1>Journeys</h1>