config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/journeys', to: 'pages#journeys'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  resources :charging_stations

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :charging_stations, only: [] do
        resources :rentals, only: [ :index, :create ]
      end

      get 'rentals/:pan_hash', :to => 'rentals#find_by_pan_hash'
      get 'charging_stations/:charging_station_id/rentals/:status', :to => 'rentals#find_all_to_be_closed'
      patch 'rentals/:id', :to => 'rentals#update'
    end
  end
end

app/models/charging_station.rb
class ChargingStation < ApplicationRecord
  has_many :rentals

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :capacity, :address, :status, presence: true

  validates :capacity, inclusion: {in: (1..80).to_a, message: "%{value} is not a valid capacity (min 1, max 80)"}
  validates :capacity, numericality: { only_integer: true }
  validates :status, inclusion: {in: [true, false] }
  validate :battery_count_cannot_be_higher_than_capacity

  private

  def battery_count_cannot_be_higher_than_capacity
    return true if (battery_count == "" || battery_count.nil?)
    errors.add(:battery_count, "Can't be higher than capacity") if battery_count > capacity
  end
end

app/controllers/charging_stations_controller.rb
class ChargingStationsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    flash.now[:notice] = "The map has been populated with random locations for demonstrative purposes."
    @charging_stations = ChargingStation.all

    @markers = @charging_stations.map do |charging_station|
      {
        position: { lat: charging_station.latitude, lng: charging_station.longitude },
        title: charging_station.location_title,
        address: charging_station.address,
        capacity: charging_station.capacity,
        battery_count: charging_station.battery_count,
        id: charging_station.id,
        status: charging_station.status
      }
    end
  end

  def show
    @charging_station = ChargingStation.find(params[:id])
    authorize @charging_station
  end

  def new
    #add redirecting if user is not admin
    @charging_station = ChargingStation.new()
    authorize @charging_station
  end

  def create
    #add redirecting if user is not admin
    @charging_station = ChargingStation.new(charging_station_params)
    if @charging_station.save!
      redirect_to charging_station_path(@charging_station)
    else
      render :new
    end
      authorize @charging_station
  end

  def edit
    @charging_station = ChargingStation.find(params[:id])
    authorize @charging_station
  end

  def update
    @charging_station = ChargingStation.find(params[:id])
    authorize @charging_station
    if @charging_station.update(charging_station_params)
      redirect_to charging_station_path(@charging_station)
    else
      render :edit
    end
  end

  private

  def charging_station_params
    params.require(:charging_station).permit(:location_title, :address, :capacity, :battery_count, :status)
  end
end

app/views/charging_stations/_charging_station_form.html.erb
<!-- Needs fixing on color of text -->

<div class="row">
  <div class="col-xs-12 col-sm-6 col-sm-offset-3">
    <%= simple_form_for @charging_station do |f| %>
    <%= f.input :location_title, input_html: { class: "text-dark"} %>
    <%= f.input :address, input_html: { class: "text-dark autocomplete"} %>
    <%= f.input :capacity %>
    <%= f.input :battery_count %>
    <%= f.input :status, label: "Active?" %>
    <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/charging_stations/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Update an existing charging station</h1>
    </div>
  </div>
  <%= render 'charging_station_form' %>
</div>

app/views/charging_stations/index.html.erb
<div
  id="map"
  style="width: 100%;
  height: 100vh;"
  data-markers="<%= @markers.to_json %>"
  data-markerimage="<%= image_path("map_marker.svg") %>"
  data-userimage="<%= image_path("map_user_marker.svg") %>"
  data-journeyspath="<%= journeys_path %>"
  data-cluster="<%= image_path("m1.png") %>"
></div>
<% content_for :page_scripts do %>
  <%= javascript_pack_tag('markerclusterer/src/markerclusterer') %>
  <%= javascript_pack_tag "map" %>
<% end %>

app/views/charging_stations/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Add a charging station</h1>
    </div>
  </div>
  <%= render 'charging_station_form' %>
</div>

app/views/charging_stations/show.html.erb
<div class="container">
  <div class="charging-station-show">
    <h3>Battery Station ID: <%= @charging_station.id %></h3>
    <p>Address: <%= @charging_station.address %></p>
    <p>Current Battery Count: <%= @charging_station.battery_count %>/<%= @charging_station.capacity %></p>
  </div>
</div>